modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/glektarssza/minecraft-expanded-gamerules/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/glektarssza/minecraft-expanded-gamerules/1.18.x/main/forge_versions.json"
displayURL="https://github.com/glektarssza/minecraft-expanded-gamerules"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "apotheosis"
mandatory = false
versionRange = "${apotheosis_version_range}"
ordering = "NONE"
side = "BOTH"