modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved."
[[mods]]
modId="expandedgamerules"
version="${file.jarVersion}"
displayName="Expanded Gamerules"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/glektarssza/minecraft-expanded-gamerules"
logoFile="expandedgamerules.png"
credits=""
authors="G'lek Tarssza" #optional
description='''
A Minecraft mod that adds a bunch of new gamerules for easier customization.
'''
