name: Bug Report
description: Report a bug in the project.
title: '[bug] '
labels:
  - Bug
body:
  - id: description
    type: textarea
    attributes:
      label: Description
      description: A short description of the bug.
    validations:
      required: true
  - id: steps
    type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide a set of steps to reproduce the issue.
    validations:
      required: true
  - id: expected
    type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - id: actual
    type: textarea
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - id: operating-system
    type: dropdown
    attributes:
      label: Operating System
      description: The operating system you are using.
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - id: java-version
    type: input
    attributes:
      label: Java Version
      description: The version of Java you are using.
    validations:
      required: true
  - id: mod-loader
    type: dropdown
    attributes:
      label: Mod Loader
      description: The mod loader you are using.
      options:
        - Fabric
        - Forge
    validations:
      required: true
  - id: mc-version
    type: input
    attributes:
      label: Minecraft Version
      description: The version of Minecraft you are using.
    validations:
      required: true
  - id: mod-version
    type: input
    attributes:
      label: Mod Version
      description: The version of the mod you are using.
    validations:
      required: true
  - id: launcher
    type: input
    attributes:
      label: Launcher
      description: The launcher you are using.
    validations:
      required: true
  - id: mod-portal
    type: dropdown
    attributes:
      label: Mod Portal
      description: The mod portal you downloaded the mod from.
      options:
        - CurseForge
        - Modrinth
        - GitHub
    validations:
      required: true
  - id: additional
    type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that may be helpful in solving the issue.
    validations:
      required: false
  - id: disclaimer
    type: checkboxes
    attributes:
      label: Disclaimer
      description: 'By submitting this issue, you state the following:'
      options:
        - label: I have searched for existing issues and this is not a duplicate.
          required: true
        - label: I have read the project's contributing guidelines.
          required: true
        - label: I have read and understood the project's code of conduct.
          required: true
