name: Pull Request
on:
  pull_request:
    branches:
      - main
      - dev
      - mc-*/main
      - mc-*/dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout Reposiory
        uses: actions/checkout@v4
        with:
          lfs: true
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - id: setup-gradle
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - id: build
        name: Build
        run: ./gradlew build
      - id: upload-common-artifacts
        name: Upload common artifacts
        uses: actions/upload-artifact@v4
        with:
          name: common-dev
          path: common/build/libs
          if-no-files-found: error
          compression-level: 0
      - id: upload-forge-artifacts
        name: Upload Forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge-dev
          path: forge/build/libs
          if-no-files-found: error
          compression-level: 0
      - id: upload-fabric-artifacts
        name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-dev
          path: fabric/build/libs
          if-no-files-found: error
          compression-level: 0
