name: Pull Request
on:
  pull_request:
jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
