name: Push
on:
  push:
jobs:
  build:
    name: Build
    permissions:
      #-- To upload artifacts
      actions: write
      #-- To clone repository
      contents: read
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
